const Map<String, dynamic> voiceParams = {
  "baidu": {
    "voice_role": [
      "度小美(普通)",
      "度小宇(普通)",
      "度逍遥(普通)",
      "度丫丫(普通)",
      "度逍遥(精品)",
      "度小鹿(精品)",
      "度博文(精品)",
      "度小童(精品)",
      "度小萌(精品)",
      "度米朵(精品)",
      "度小娇(精品)"
    ],
    "role_number": [0, 1, 3, 4, 5003, 5118, 106, 110, 111, 103, 5],
    "aue": ["wav", "mp3", "mp3-16k", "mp3-48k", "pcm-16k", "pcm-8k"],
    "aue_num": [3, 4, 5, 6],
    "audition_url": "https://cloud.baidu.com/product/speech/tts_online",
    "short_voice_url": "https://tsn.baidu.com/text2audio",
    "long_voice_create_url": "https://aip.baidubce.com/rpc/2.0/tts/v1/create",
    "long_voice_query_url": "https://aip.baidubce.com/rpc/2.0/tts/v1/query",
    "get_access_token_url": "https://aip.baidubce.com/oauth/2.0/token"
  },
  "ali": {
    "voice_role": [
      "知妙_多情感(多种情感女声-中英场景)",
      "知甜_多情感(多种情感女声-通用场景)",
      "知米_多情感(多种情感女声-通用场景)",
      "知燕_多情感(多种情感女声-通用场景)",
      "知贝_多情感(多种情感童声-通用场景)",
      "若兮(温柔女声-通用场景)",
      "思琪(温柔女声-通用场景)",
      "艾琪(温柔女声-通用场景)",
      "小云(标准女声-通用场景)",
      "思佳(标准女声-通用场景)",
      "艾佳(标准女声-通用场景)",
      "柜姐(亲切女声-通用场景)",
      "宁儿(标准女声-通用场景)",
      "瑞琳(标准女声-通用场景)",
      "思诚(标准男声-通用场景)",
      "小刚(标准男声-通用场景)",
      "Stella(知性女声-通用场景)",
      "Stanley(沉稳男声-通用场景)",
      "Kenny(沉稳男声-通用场景)",
      "Rosa(自然女声-通用场景)",
      "艾诚(标准男声-通用场景)",
      "艾达(标准男声-通用场景)",
      "知媛(普通话女声-通用场景)",
      "知柜(普通话女声-通用场景)",
      "知雅(普通话女声-通用场景)",
      "知悦(普通话女声-通用场景)",
      "知硕(普通话男声-通用场景)",
      "知达(普通话男声-通用场景)",
      "知莎(普通话女声-通用场景)",
      "思悦(温柔女声-客服场景)",
      "艾雅(严厉女声-客服场景)",
      "艾夏(亲和女声-客服场景)",
      "艾美(甜美女声-客服场景)",
      "艾雨(自然女声-客服场景)",
      "艾悦(温柔女声-客服场景)",
      "艾婧(严厉女声-客服场景)",
      "小美(甜美女声-客服场景)",
      "艾硕(自然男声-客服场景)",
      "艾娜(浙普女声-客服场景)",
      "伊娜(浙普女声-客服场景)",
      "思婧(严厉女声-客服场景)",
      "思彤(儿童音-童声场景)",
      "杰力豆(治愈童声-童声场景)",
      "小北(萝莉女声-童声场景)",
      "艾彤(儿童音-童声场景)",
      "艾薇(萝莉女声-童声场景)",
      "艾宝(萝莉女声-童声场景)",
      "Harry(英音男声-英文场景)",
      "ava(美语女声-英文场景)",
      "Abby(美音女声-英文场景)",
      "Andy(美音男声-英文场景)",
      "Eric(英音男声-英文场景)",
      "Emily(英音女声-英文场景)",
      "Luna(英音女声-英文场景)",
      "Luca(英音男声-英文场景)",
      "Wendy(英音女声-英文场景)",
      "William(英音男声-英文场景)",
      "Olivia(英音女声-英文场景)",
      "Annie(美语女声-英文场景)",
      "Lydia(英中双语女声-英文场景)",
      "智香(日语女声-日文场景)",
      "智也(日语男声-日文场景)",
      "姗姗(粤语女声-方言场景)",
      "大虎(东北话男声-方言场景)",
      "翠姐(东北话女声-方言场景)",
      "小泽(湖南重口音男声-方言场景)",
      "小玥(四川话女声-方言场景)",
      "青青(台湾话女声-方言场景)",
      "佳佳(粤语女声-方言场景)",
      "Kelly(香港粤语女声-方言场景)",
      "桃子(粤语女声-方言场景)",
      "艾侃(天津话男声-方言场景)",
      "马树(儿童剧男声-通用场景)",
      "悦儿(儿童剧女声-通用场景)",
      "小仙(亲切女声-直播场景)",
      "知飞(激昂解说-超高清场景)",
      "知伦(悬疑解说-超高清场景)",
      "猫小美(活力女声-直播场景)",
      "艾飞(激昂解说-直播场景)",
      "亚群(卖场广播-直播场景)",
      "巧薇(卖场广播-直播场景)",
      "艾伦(悬疑解说-直播场景)",
      "知猫(普通话女声-直播场景)",
      "老铁(东北老铁-直播场景)",
      "老妹(吆喝女声-直播场景)",
      "Tala(菲律宾语女声-菲律宾语场景)",
      "Tien(越南语女声-越南语场景)",
      "Becca(美语客服女声-美式英语)",
      "Kyong(韩语女声-韩语场景)",
      "masha(俄语女声-俄语场景)",
      "Farah(马来语女声-纯马来语场景)",
      "Indah(印尼语女声-纯印尼语场景)",
      "camila(西班牙语女声-西班牙语场景)",
      "perla(意大利语女声-意大利语场景)"
    ],
    "voice_code": [
      "zhimiao_emo",
      "zhitian_emo",
      "zhimi_emo",
      "zhiyan_emo",
      "zhibei_emo",
      "ruoxi",
      "siqi",
      "aiqi",
      "xiaoyun",
      "sijia",
      "aijia",
      "guijie",
      "ninger",
      "ruilin",
      "sicheng",
      "xiaogang",
      "stella",
      "stanley",
      "kenny",
      "rosa",
      "aicheng",
      "aida",
      "zhiyuan",
      "zhigui",
      "zhiya",
      "zhiyue",
      "zhishuo",
      "zhida",
      "zhisha",
      "siyue",
      "aiya",
      "aixia",
      "aimei",
      "aiyu",
      "aiyue",
      "aijing",
      "xiaomei",
      "aishuo",
      "aina",
      "yina",
      "sijing",
      "sitong",
      "jielidou",
      "xiaobei",
      "aitong",
      "aiwei",
      "aibao",
      "harry",
      "ava",
      "abby",
      "andy",
      "eric",
      "emily",
      "luna",
      "luca",
      "wendy",
      "william",
      "olivia",
      "annie",
      "lydia",
      "zhixiang",
      "zhiye",
      "shanshan",
      "dahu",
      "cuijie",
      "xiaoze",
      "xiaoyue",
      "qingqing",
      "jiajia",
      "kelly",
      "taozi",
      "aikan",
      "mashu",
      "yuer",
      "xiaoxian",
      "zhifei",
      "zhilun",
      "maoxiaomei",
      "aifei",
      "yaqun",
      "qiaowei",
      "ailun",
      "zhimao",
      "laotie",
      "laomei",
      "tala",
      "tien",
      "becca",
      "kyong",
      "mesha",
      "farah",
      "indah",
      "camila",
      "perla"
    ],
    "emotion_category": {
      "zhimiao_emo_en": [
        "neutral",
        "serious",
        "sad",
        "disgust",
        "jealousy",
        "embarrassed",
        "happy",
        "fear",
        "surprise",
        "frustrated",
        "affectionate",
        "gentle",
        "angry",
        "newscast",
        "customer-service",
        "story",
        "living"
      ],
      "zhimi_emo_en": [
        "neutral",
        "happy",
        "angry",
        "sad",
        "fear",
        "hate",
        "surprise"
      ],
      "zhiyan_emo_en": [
        "neutral",
        "happy",
        "angry",
        "sad",
        "fear",
        "hate",
        "surprise",
        "arousal"
      ],
      "zhibei_emo_en": [
        "neutral",
        "happy",
        "angry",
        "sad",
        "fear",
        "hate",
        "surprise"
      ],
      "zhitian_emo_en": [
        "neutral",
        "happy",
        "angry",
        "sad",
        "fear",
        "hate",
        "surprise"
      ],
      "zhimiao_emo_zh": [
        "中性",
        "严肃",
        "悲伤",
        "厌恶",
        "嫉妒",
        "尴尬",
        "开心",
        "害怕",
        "惊讶",
        "沮丧",
        "深情",
        "温柔",
        "生气",
        "播报",
        "客服",
        "小说",
        "直播"
      ],
      "zhimi_emo_zh": ["中性", "开心", "生气", "悲伤", "害怕", "憎恨", "惊讶"],
      "zhiyan_emo_zh": ["中性", "开心", "生气", "悲伤", "害怕", "憎恨", "惊讶", "激动"],
      "zhibei_emo_zh": ["中性", "开心", "生气", "悲伤", "害怕", "憎恨", "惊讶"],
      "zhitian_emo_zh": ["中性", "开心", "生气", "悲伤", "害怕", "憎恨", "惊讶"]
    },
    "aue": ["wav", "mp3", "pcm"],
    "short_voice_url":
        "https://nls-gateway-cn-shanghai.aliyuncs.com/stream/v1/tts",
    "long_voice_url":
        "https://nls-gateway.cn-shanghai.aliyuncs.com/rest/v1/tts/async"
  },
  "huawei": {
    "voice_role": [
      "小琪(普通-标准女声)",
      "小雯(普通-柔美女声)",
      "小宇(普通-标准男声)",
      "小夏(普通-热情女声)",
      "小燕(普通-温柔女声)",
      "小倩(普通-成熟女声)",
      "小王(普通-童声)",
      "小呆(普通-呆萌童声)",
      "小婧(普通-俏皮女声)",
      "小宋(普通-激昂男声)",
      "cameal(普通-英文女声)",
      "华小夏(精品-热情女声)",
      "华小唯(精品-嗲柔女声)",
      "华小颜(精品-严厉女声)",
      "华晓阳(精品-朝气男声)",
      "华晓刚(精品-利落男声)",
      "华小雯(精品-柔美女声)",
      "华小美(精品-温柔女声)",
      "华小飞(精品-朝气男声)",
      "华小璐(精品-知性女声)",
      "华小靓(精品-嘹亮女声)",
      "华晓东(精品-成熟男声)",
      "华小蕊(精品-知性女声)",
      "华小萱(精品-台湾女声)",
      "华小闽(精品-闽南女声)",
      "华小舒(精品-舒缓女声)",
      "华女侠(精品-武侠女生)",
      "华晓悬(精品-悬疑男声)",
      "华小龙(精品-朝气男声)",
      "华小汝(精品-柔美女声)",
      "华小涵(精品-知性女声)",
      "华小宁(精品-沉稳男声)",
      "华小珍(精品-温柔女声)",
      "alvin(精品-成熟英文男声)",
      "amy(精品-成熟英文女声)"
    ],
    "voice_code": [
      "chinese_xiaoqi_common",
      "chinese_xiaowen_common",
      "chinese_xiaoyu_common",
      "chinese_xiaoxia_common",
      "chinese_xiaoyan_common",
      "chinese_xiaoqian_common",
      "chinese_xiaowang_common",
      "chinese_xiaodai_common",
      "chinese_xiaojing_common",
      "chinese_xiaosong_common",
      "english_cameal_common",
      "chinese_huaxiaoxia_common",
      "chinese_huaxiaowei_common",
      "chinese_huaxiaoyan_common",
      "chinese_huaxiaoyang_common",
      "chinese_huaxiaogang_common",
      "chinese_huaxiaowen_common",
      "chinese_huaxiaomei_common",
      "chinese_huaxiaofei_common",
      "chinese_huaxiaolu_common",
      "chinese_huaxiaoliang_common",
      "chinese_huaxiaodong_common",
      "chinese_huaxiaorui_common",
      "chinese_huaxiaoxuan_common",
      "chinese_huaxiaomin_common",
      "chinese_huaxiaoshu_common",
      "chinese_huanvxia_literature",
      "chinese_huaxiaoxuan_literature",
      "chinese_huaxiaolong_common",
      "chinese_huaxiaoru_common",
      "chinese_huaxiaohan_common",
      "chinese_huaxiaoning_common",
      "chinese_huaxiaozhen_common",
      "english_alvin_common",
      "english_amy_common"
    ],
    "aue": ["wav", "mp3", "pcm"],
    "tts_url":
        "https://sis-ext.cn-east-3.myhuaweicloud.com/v1/528c3886649b45ebb28463ce1b9fdb6b/tts",
    "get_access_token_url":
        "https://iam.cn-east-3.myhuaweicloud.com/v3/auth/tokens"
  },
  "azure": {
    "speech_list_url":
        "https://eastus.tts.speech.microsoft.com/cognitiveservices/voices/list",
    "aue": ["wav", "mp3", "pcm"],
    "emotion_category": {
      "Xiaoxiao": {
        "styles_en": [
          "default",
          "assistant",
          "chat",
          "customerservice",
          "newscast",
          "affectionate",
          "angry",
          "calm",
          "cheerful",
          "disgruntled",
          "fearful",
          "gentle",
          "lyrical",
          "sad",
          "serious",
          "poetry-reading",
          "friendly"
        ],
        "styles_zh": [
          "默认",
          "助理",
          "闲聊",
          "客服",
          "新闻广播",
          "撒娇",
          "发怒",
          "平静",
          "愉快",
          "不满",
          "担心",
          "温和",
          "抒情",
          "悲哀",
          "严厉",
          "诗歌阅读",
          "友爱"
        ]
      },
      "Yunxi": {
        "styles_en": [
          "default",
          "narration-relaxed",
          "embarrassed",
          "fearful",
          "cheerful",
          "disgruntled",
          "serious",
          "angry",
          "sad",
          "depressed",
          "chat",
          "assistant",
          "newscast"
        ],
        "styles_zh": [
          "默认",
          "叙述放松",
          "尴尬",
          "担心",
          "愉快",
          "不满",
          "严厉",
          "发怒",
          "悲哀",
          "沮丧",
          "闲聊",
          "助理",
          "新闻广播"
        ],
        "roles_en": ["default", "Narrator", "YoungAdultMale", "Boy"],
        "roles_zh": ["默认", "旁白", "青年男性", "男孩"]
      },
      "Yunjian": {
        "styles_en": [
          "default",
          "narration-relaxed",
          "sports-commentary",
          "sports-commentary-excited"
        ],
        "styles_zh": ["默认", "叙述放松", "体育评论", "体育解说激动"]
      },
      "Xiaoyi": {
        "styles_en": [
          "default",
          "angry",
          "disgruntled",
          "affectionate",
          "cheerful",
          "fearful",
          "sad",
          "embarrassed",
          "serious",
          "gentle"
        ],
        "styles_zh": [
          "默认",
          "发怒",
          "不满",
          "撒娇",
          "愉快",
          "担心",
          "悲哀",
          "尴尬",
          "严厉",
          "温和"
        ]
      },
      "Yunyang": {
        "styles_en": [
          "default",
          "customerservice",
          "narration-professional",
          "newscast-casual"
        ],
        "styles_zh": ["默认", "客服", "叙述专业人员", "新闻广播休闲"]
      },
      "Xiaohan": {
        "styles_en": [
          "default",
          "calm",
          "fearful",
          "cheerful",
          "disgruntled",
          "serious",
          "angry",
          "sad",
          "gentle",
          "affectionate",
          "embarrassed"
        ],
        "styles_zh": [
          "默认",
          "平静",
          "担心",
          "愉快",
          "不满",
          "严厉",
          "发怒",
          "悲哀",
          "温和",
          "撒娇",
          "尴尬"
        ]
      },
      "Xiaomeng": {
        "styles_en": ["default", "chat"],
        "styles_zh": ["默认", "闲聊"]
      },
      "Xiaomo": {
        "styles_en": [
          "default",
          "embarrassed",
          "calm",
          "fearful",
          "cheerful",
          "disgruntled",
          "serious",
          "angry",
          "sad",
          "depressed",
          "affectionate",
          "gentle",
          "envious"
        ],
        "styles_zh": [
          "默认",
          "尴尬",
          "平静",
          "担心",
          "愉快",
          "不满",
          "严厉",
          "发怒",
          "悲哀",
          "沮丧",
          "撒娇",
          "温和",
          "嫉妒"
        ],
        "roles_en": [
          "default",
          "YoungAdultFemale",
          "YoungAdultMale",
          "OlderAdultFemale",
          "OlderAdultMale",
          "SeniorFemale",
          "SeniorMale",
          "Girl",
          "Boy"
        ],
        "roles_zh": [
          "默认",
          "年轻女性",
          "青年男性",
          "老年人成年女性",
          "老年人成年男性",
          "老年女性",
          "老年男性",
          "女孩",
          "男孩"
        ]
      },
      "Xiaorui": {
        "styles_en": ["default", "calm", "fearful", "angry", "sad"],
        "styles_zh": ["默认", "平静", "担心", "发怒", "悲哀"]
      },
      "Xiaoshuang": {
        "styles_en": ["default", "chat"],
        "styles_zh": ["默认", "闲聊"]
      },
      "Xiaoxuan": {
        "styles_en": [
          "default",
          "calm",
          "fearful",
          "cheerful",
          "disgruntled",
          "serious",
          "angry",
          "gentle",
          "depressed"
        ],
        "styles_zh": ["默认", "平静", "担心", "愉快", "不满", "严厉", "发怒", "温和", "沮丧"],
        "roles_en": [
          "default",
          "YoungAdultFemale",
          "YoungAdultMale",
          "OlderAdultFemale",
          "OlderAdultMale",
          "SeniorFemale",
          "SeniorMale",
          "Girl",
          "Boy"
        ],
        "roles_zh": [
          "默认",
          "年轻女性",
          "青年男性",
          "老年人成年女性",
          "老年人成年男性",
          "老年女性",
          "老年男性",
          "女孩",
          "男孩"
        ]
      },
      "Xiaozhen": {
        "styles_en": [
          "default",
          "angry",
          "disgruntled",
          "cheerful",
          "fearful",
          "sad",
          "serious"
        ],
        "styles_zh": ["默认", "发怒", "不满", "愉快", "担心", "悲哀", "严厉"]
      },
      "Yunfeng": {
        "styles_en": [
          "default",
          "angry",
          "disgruntled",
          "cheerful",
          "fearful",
          "sad",
          "serious",
          "depressed"
        ],
        "styles_zh": ["默认", "发怒", "不满", "愉快", "担心", "悲哀", "严厉", "沮丧"]
      },
      "Yunhao": {
        "styles_en": ["default", "advertisement-upbeat"],
        "styles_zh": ["默认", "广告欢快"]
      },
      "Yunxia": {
        "styles_en": ["default", "calm", "fearful", "cheerful", "angry", "sad"],
        "styles_zh": ["默认", "平静", "担心", "愉快", "发怒", "悲哀"]
      },
      "Yunye": {
        "styles_en": [
          "default",
          "embarrassed",
          "calm",
          "fearful",
          "cheerful",
          "disgruntled",
          "serious",
          "angry",
          "sad"
        ],
        "styles_zh": ["默认", "尴尬", "平静", "担心", "愉快", "不满", "严厉", "发怒", "悲哀"],
        "roles_en": [
          "default",
          "YoungAdultFemale",
          "YoungAdultMale",
          "OlderAdultFemale",
          "OlderAdultMale",
          "SeniorFemale",
          "SeniorMale",
          "Girl",
          "Boy"
        ],
        "roles_zh": [
          "默认",
          "年轻女性",
          "青年男性",
          "老年人成年女性",
          "老年人成年男性",
          "老年女性",
          "老年男性",
          "女孩",
          "男孩"
        ]
      },
      "Yunze": {
        "styles_en": [
          "default",
          "calm",
          "fearful",
          "cheerful",
          "disgruntled",
          "serious",
          "angry",
          "sad",
          "depressed",
          "documentary-narration"
        ],
        "styles_zh": [
          "默认",
          "平静",
          "担心",
          "愉快",
          "不满",
          "严厉",
          "发怒",
          "悲哀",
          "沮丧",
          "纪实叙事"
        ],
        "roles_en": ["default", "OlderAdultMale", "SeniorMale"],
        "roles_zh": ["默认", "老年人成年男性", "老年男性"]
      }
    },
    "voice_number": 36,
    "voice_role": [
      "晓彤(女-中文(吴语，简体))",
      "云哲(男-中文(吴语，简体))",
      "晓敏(女-中文(粤语，简体))",
      "云松(男-中文(粤语，简体))",
      "晓晓(女-中文(普通话，简体，多情感))",
      "云希(男-中文(普通话，简体，多情感，多角色))",
      "云健(男-中文(普通话，简体))",
      "晓伊(女-中文(普通话，简体，多情感))",
      "云扬(男-中文(普通话，简体，多情感))",
      "晓辰(女-中文(普通话，简体))",
      "晓涵(女-中文(普通话，简体，多情感))",
      "晓梦(女-中文(普通话，简体))",
      "晓墨(女-中文(普通话，简体，多情感，多角色))",
      "晓秋(女-中文(普通话，简体))",
      "晓睿(女-中文(普通话，简体，多情感))",
      "晓双(女-中文(普通话，简体))",
      "晓萱(女-中文(普通话，简体，多情感，多角色))",
      "晓颜(女-中文(普通话，简体))",
      "晓悠(女-中文(普通话，简体))",
      "晓甄(女-中文(普通话，简体))",
      "云枫(男-中文(普通话，简体，多情感))",
      "云皓(男-中文(普通话，简体，多情感))",
      "云夏(男-中文(普通话，简体，多情感))",
      "云野(男-中文(普通话，简体，多情感，多角色))",
      "云泽(男-中文(普通话，简体，多情感，多角色))",
      "云登(男-中文(中原官话河南，简体))",
      "晓北(女-中文(东北官话，简体))",
      "晓妮(女-中文(中原官话陕西，简体))",
      "云翔(男-中文(冀鲁官话，简体))",
      "云希(男-中文(四川话，简体))",
      "曉曼(女-中文(粤语，繁体))",
      "雲龍(男-中文(粤语，繁体))",
      "曉佳(女-中文(粤语，繁体))",
      "曉臻(女-中文(台湾普通话))",
      "雲哲(男-中文(台湾普通话))",
      "曉雨(女-中文(台湾普通话))"
    ],
    "voice_code": [
      "wuu-CN-XiaotongNeural",
      "wuu-CN-YunzheNeural",
      "yue-CN-XiaoMinNeural",
      "yue-CN-YunSongNeural",
      "zh-CN-XiaoxiaoNeural",
      "zh-CN-YunxiNeural",
      "zh-CN-YunjianNeural",
      "zh-CN-XiaoyiNeural",
      "zh-CN-YunyangNeural",
      "zh-CN-XiaochenNeural",
      "zh-CN-XiaohanNeural",
      "zh-CN-XiaomengNeural",
      "zh-CN-XiaomoNeural",
      "zh-CN-XiaoqiuNeural",
      "zh-CN-XiaoruiNeural",
      "zh-CN-XiaoshuangNeural",
      "zh-CN-XiaoxuanNeural",
      "zh-CN-XiaoyanNeural",
      "zh-CN-XiaoyouNeural",
      "zh-CN-XiaozhenNeural",
      "zh-CN-YunfengNeural",
      "zh-CN-YunhaoNeural",
      "zh-CN-YunxiaNeural",
      "zh-CN-YunyeNeural",
      "zh-CN-YunzeNeural",
      "zh-CN-henan-YundengNeural",
      "zh-CN-liaoning-XiaobeiNeural",
      "zh-CN-shaanxi-XiaoniNeural",
      "zh-CN-shandong-YunxiangNeural",
      "zh-CN-sichuan-YunxiNeural",
      "zh-HK-HiuMaanNeural",
      "zh-HK-WanLungNeural",
      "zh-HK-HiuGaaiNeural",
      "zh-TW-HsiaoChenNeural",
      "zh-TW-YunJheNeural",
      "zh-TW-HsiaoYuNeural"
    ]
  },
  "amazon": {}
};
