const Map<String, dynamic> draftContent ={
  "canvas_config": {
    "height": 1440,
    "ratio": "original",
    "width": 1920
  },
  "color_space": 0,
  "config": {
    "adjust_max_index": 1,
    "attachment_info": [],
    "combination_max_index": 1,
    "export_range": null,
    "extract_audio_last_index": 1,
    "lyrics_recognition_id": "",
    "lyrics_sync": true,
    "lyrics_taskinfo": [],
    "maintrack_adsorb": true,
    "material_save_mode": 0,
    "original_sound_last_index": 1,
    "record_audio_last_index": 1,
    "sticker_max_index": 1,
    "subtitle_recognition_id": "",
    "subtitle_sync": true,
    "subtitle_taskinfo": [],
    "system_font_list": [],
    "video_mute": false,
    "zoom_info_params": null
  },
  "cover": null,
  "create_time": 0,
  "duration": 0,
  "extra_info": null,
  "fps": 60.0,
  "free_render_index_mode_on": false,
  "group_container": null,
  "id": "BCAAD120-870E-4180-B762-8EA12025EFB2",
  "keyframe_graph_list": [],
  "keyframes": {
    "adjusts": [],
    "audios": [],
    "effects": [],
    "filters": [],
    "handwrites": [],
    "stickers": [],
    "texts": [],
    "videos": []
  },
  "last_modified_platform": {
    "app_id": 3704,
    "app_source": "lv",
    "app_version": "4.3.0",
    "device_id": "",
    "hard_disk_id": "",
    "mac_address": "",
    "os": "",
    "os_version": ""
  },
  "materials": {
    "audio_balances": [],
    "audio_effects": [],
    "audio_fades": [],
    "audios": [],
    "beats": [],
    "canvases": [
      {
        "album_image": "",
        "blur": 0.0,
        "color": "",
        "id": "1E519D8D-680E-489c-9BC4-57BBFC3469BE",
        "image": "",
        "image_id": "",
        "image_name": "",
        "source_platform": 0,
        "team_id": "",
        "type": "canvas_color"
      }
    ],
    "chromas": [],
    "color_curves": [],
    "drafts": [],
    "effects": [],
    "green_screens": [],
    "handwrites": [],
    "hsl": [],
    "images": [],
    "log_color_wheels": [],
    "manual_deformations": [],
    "masks": [],
    "material_animations": [],
    "material_colors": [],
    "placeholders": [],
    "plugin_effects": [],
    "primary_color_wheels": [],
    "realtime_denoises": [],
    "sound_channel_mappings": [
      {
        "audio_channel_mapping": 0,
        "id": "138C5780-C5C2-4c05-98BB-53EF12AA08FD",
        "is_config_open": false,
        "type": ""
      }
    ],
    "speeds": [
      {
        "curve_speed": null,
        "id": "D504BC86-5C60-4e99-83CA-FE8E85380E26",
        "mode": 0,
        "speed": 1.0,
        "type": "speed"
      }
    ],
    "stickers": [],
    "tail_leaders": [],
    "text_templates": [],
    "texts": [],
    "transitions": [],
    "video_effects": [],
    "video_trackings": [],
    "videos": []
  },
  "mutable_config": null,
  "name": "",
  "new_version": "77.0.0",
  "platform": {
    "app_id": 3704,
    "app_source": "lv",
    "app_version": "4.3.0",
    "device_id": "",
    "hard_disk_id": "",
    "mac_address": "",
    "os": "",
    "os_version": ""
  },
  "relationships": [],
  "render_index_track_mode_on": false,
  "retouch_cover": null,
  "source": "default",
  "static_cover_image_path": "",
  "tracks": [],
  "update_time": 0,
  "version": 360000
};